# Form implementation generated from reading ui file 'c:\Users\lapto\Documents\Ingenieria\Proyectos\Lenguajes - Proyecto 2\Principal.ui'
#
# Created by: PyQt6 UI code generator 6.2.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ventana(object):
    def setupUi(self, ventana):
        ventana.setObjectName("ventana")
        ventana.resize(1262, 684)
        ventana.setStyleSheet("background-color:rgb(50, 50, 50)")
        self.centralwidget = QtWidgets.QWidget(ventana)
        self.centralwidget.setObjectName("centralwidget")
        self.line_6 = QtWidgets.QFrame(self.centralwidget)
        self.line_6.setGeometry(QtCore.QRect(20, 160, 1221, 16))
        self.line_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.line_6.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_6.setObjectName("line_6")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 1225, 151))
        self.label.setStyleSheet("background-color: rgb(59, 59, 59)")
        self.label.setText("")
        self.label.setObjectName("label")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(630, 170, 20, 501))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 311, 131))
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 55pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(350, 10, 20, 151))
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(380, 20, 241, 21))
        self.label_3.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Trebuchet MS\";")
        self.label_3.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setGeometry(QtCore.QRect(630, 10, 16, 151))
        self.line_4.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 20, 590, 21))
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 12pt \"Trebuchet MS\";")
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QPushButton(self.centralwidget)
        self.error.setGeometry(QtCore.QRect(650, 50, 590, 30))
        self.error.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Trebuchet MS\";")
        self.error.setObjectName("error")
        self.token = QtWidgets.QPushButton(self.centralwidget)
        self.token.setGeometry(QtCore.QRect(650, 90, 590, 30))
        self.token.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Trebuchet MS\";")
        self.token.setObjectName("token")
        self.arbol = QtWidgets.QPushButton(self.centralwidget)
        self.arbol.setGeometry(QtCore.QRect(650, 130, 590, 30))
        self.arbol.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Trebuchet MS\";")
        self.arbol.setObjectName("arbol")
        self.cargar = QtWidgets.QPushButton(self.centralwidget)
        self.cargar.setGeometry(QtCore.QRect(380, 50, 241, 45))
        self.cargar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Trebuchet MS\";")
        self.cargar.setObjectName("cargar")
        self.analizar = QtWidgets.QPushButton(self.centralwidget)
        self.analizar.setGeometry(QtCore.QRect(380, 110, 241, 45))
        self.analizar.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: italic 10pt \"Trebuchet MS\";")
        self.analizar.setObjectName("analizar")
        self.texto = QtWidgets.QTextEdit(self.centralwidget)
        self.texto.setGeometry(QtCore.QRect(20, 180, 611, 481))
        self.texto.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: italic 14pt \"Bahnschrift\";")
        self.texto.setObjectName("texto")
        self.consola = QtWidgets.QTextEdit(self.centralwidget)
        self.consola.setGeometry(QtCore.QRect(650, 180, 595, 481))
        self.consola.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 14pt \"Bahnschrift\";")
        self.consola.setReadOnly(True)
        self.consola.setObjectName("consola")
        self.label.raise_()
        self.line_6.raise_()
        self.line_2.raise_()
        self.label_2.raise_()
        self.line_3.raise_()
        self.label_3.raise_()
        self.line_4.raise_()
        self.label_4.raise_()
        self.error.raise_()
        self.token.raise_()
        self.arbol.raise_()
        self.cargar.raise_()
        self.analizar.raise_()
        self.texto.raise_()
        self.consola.raise_()
        ventana.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ventana)
        self.statusbar.setObjectName("statusbar")
        ventana.setStatusBar(self.statusbar)

        self.retranslateUi(ventana)
        QtCore.QMetaObject.connectSlotsByName(ventana)

    def retranslateUi(self, ventana):
        _translate = QtCore.QCoreApplication.translate
        ventana.setWindowTitle(_translate("ventana", "Principal"))
        self.label_2.setText(_translate("ventana", "PR2 V1.0"))
        self.label_3.setText(_translate("ventana", "Codigo"))
        self.label_4.setText(_translate("ventana", "Reportes"))
        self.error.setText(_translate("ventana", "Errores"))
        self.token.setText(_translate("ventana", "Tokens"))
        self.arbol.setText(_translate("ventana", "Arbol de Derivación"))
        self.cargar.setText(_translate("ventana", "Cargar Archivo"))
        self.analizar.setText(_translate("ventana", "Analizar Codigo"))
